# Application bindings
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(hl-cmd-terminal-cwd)"
bindd = SUPER SHIFT, RETURN, Browser, exec, hl-launch-browser
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER ALT SHIFT, F, File manager (cwd), exec, uwsm-app -- nautilus --new-window "$(hl-cmd-terminal-cwd)"
bindd = SUPER SHIFT, B, Browser, exec, hl-launch-browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, hl-launch-browser --private
bindd = SUPER SHIFT, N, Editor, exec, hl-launch-editor
bind = SUPER, Q, Terminal, exec, uwsm-app -- kitty

# Add extra bindings
# bindd = SUPER SHIFT, A, ChatGPT, exec, hl-launch-webapp "https://chatgpt.com"
# bindd = SUPER SHIFT, R, exec, alacritty -e ssh your-server

# Overwrite existing bindings, like putting Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, menu, exec, hl-menu
